# Generated by Django 2.0.13 on 2019-07-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190705_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sportart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
