# Generated by Django 2.0.13 on 2019-07-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190703_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sports'),
        ),
        migrations.AddField(
            model_name='post',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
