# Generated by Django 2.0.13 on 2019-07-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190703_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='sports'),
        ),
        migrations.AlterField(
            model_name='post',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sportart',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
