# Generated by Django 2.0.13 on 2019-07-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190703_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sportart',
            field=models.CharField(max_length=200),
        ),
    ]
